table 'Tableaux 3'
	lineageTag: c5627cee-6a33-4ce8-afc6-883f80de52d3

	column 'Matricule collaborateur'
		dataType: int64
		formatString: 0
		lineageTag: ab08bf83-1d95-4b80-b75b-8de821ce0309
		summarizeBy: none
		sourceColumn: Matricule collaborateur

		annotation SummarizationSetBy = Automatic

	column Souhait
		dataType: string
		lineageTag: 7196918e-ce7a-4a02-a572-2b5a3c50c99c
		summarizeBy: none
		sourceColumn: Souhait

		annotation SummarizationSetBy = Automatic

	column Réponse/Proposition
		dataType: string
		lineageTag: fd1795c4-e40e-4b63-8923-b7bf2f928b43
		summarizeBy: none
		sourceColumn: Réponse/Proposition

		annotation SummarizationSetBy = Automatic

	partition 'Tableaux 3' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\myriam.pages\OneDrive - Butagaz\Documents\Personnel\Fichier global anonymisé EAE 2025.xlsx"), null, true),
				    #"Tableaux 3_Sheet" = Source{[Item="Tableaux 3",Kind="Sheet"]}[Data],
				    #"En-têtes promus" = Table.PromoteHeaders(#"Tableaux 3_Sheet", [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"Statut", type text}, {"Prénom collaborateur", type text}, {"Nom collaborateur", type text}, {"Matricule collaborateur", Int64.Type}, {"Rôle collaborateur", type text}, {"Date d'embauche collaborateur", type date}, {"Catégorie contrat collaborateur", type text}, {"Entreprise collaborateur", type text}, {"Service collaborateur", type text}, {"Direction collaborateur", type text}, {"Nom manager", type text}, {"Matricule manager", Int64.Type}, {"Rôle manager", type text}, {"Date d'embauche manager", type date}, {"Catégorie contrat manager", type text}, {"Entreprise manager", type text}, {"Service manager", type text}, {"Direction manager", type text}, {"Etat collaborateur", type text}, {"Date de signature du collaborateur", type date}, {"Etat manager", type text}, {"Date de signature du manager", type date}, {"Souhait", type text}, {"Réponse/Proposition", type text}}),
				    #"Autres colonnes supprimées" = Table.SelectColumns(#"Type modifié",{"Matricule collaborateur", "Souhait", "Réponse/Proposition"}),
				    #"Lignes vides supprimées" = Table.SelectRows(#"Autres colonnes supprimées", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Personnalisée ajoutée" = Table.AddColumn(#"Lignes vides supprimées", "Personnalisé", each "CONTENU MASQUE"),
				    #"Colonnes supprimées" = Table.RemoveColumns(#"Personnalisée ajoutée",{"Souhait"}),
				    #"Colonnes renommées" = Table.RenameColumns(#"Colonnes supprimées",{{"Personnalisé", "Souhait"}}),
				    #"Personnalisée ajoutée1" = Table.AddColumn(#"Colonnes renommées", "Personnalisé", each "CONTENU MASQUE"),
				    #"Colonnes supprimées1" = Table.RemoveColumns(#"Personnalisée ajoutée1",{"Réponse/Proposition"}),
				    #"Colonnes renommées1" = Table.RenameColumns(#"Colonnes supprimées1",{{"Personnalisé", "Réponse/Proposition"}})
				in
				    #"Colonnes renommées1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

